### ISSUE TITLE
Server Invite Link in the Readme is invalid.

### ISSUE THREAD

**Issue by GreemDev** [jgayfer/spirit#77]
not an issue with code, but I figured I'd make it known to you

**Comment by jgayfer** [comment]
Thank you

**Comment by jgayfer** [comment]
Closing for sake of finality. RIP Spirit.

**Comment by GreemDev** [comment]
> 
> 
> Closing for sake of finality. RIP Spirit.

@jgayfer 
Any reason you discontinued Spirit? I actually liked this project and, while I tried contributing a year or 2 ago, I actually had no idea what the fuck I was doing :)
