### ISSUE TITLE
Add link to support server in help message

### ISSUE THREAD

**Issue by jgayfer** [jgayfer/spirit#8]

**Comment by 4rcane** [comment]
Potential Improvement: send user to information or release notes instead of general channel, that way they are more strongly encouraged to look at information that we have already covered.

**Comment by jgayfer** [comment]
Good idea. I will need to make a new link and update reddit/bungie.

EDIT: Actually that's probably fine... i'll just make a new one for the help message. I'm lazy.
EDIT2: Done!

**Comment by 4rcane** [comment]
Verified.
